### ISSUE TITLE
Install on Superuser-8.apk fails on maguro (unrooted)

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#50]
Is it supposed to support an unrooted device with the beta installed? If not supported, a better error message should be given.

I start the app and it wants to update the su binary. Choose recovery.

adb logcat:

I/ActivityManager(  393): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.koushikdutta.superuser/.MainActivity bnds=[360,567][360,567]} from pid 718
I/ActivityManager(  393): Start proc com.koushikdutta.superuser for activity com.koushikdutta.superuser/.MainActivity: pid=2234 uid=10137 gids={50137, 1028}
W/System.err( 2234):    at com.koushikdutta.superuser.MainActivity.checkSu(MainActivity.java:227)
W/System.err( 2234):    at com.koushikdutta.superuser.MainActivity$6.run(MainActivity.java:252)
I/ActivityManager(  393): Displayed com.koushikdutta.superuser/.MainActivity: +852ms
W/System.err( 2234):    at com.koushikdutta.superuser.MainActivity$2.run(MainActivity.java:123)

**Comment by ogr3** [comment]
Play description clearly states su needed for install. Closing this.
